apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-client
  labels:
    app: elastic
    deployment: production
    role: client
spec:
  replicas: 1
  template:
    metadata:
      name: elasticsearch-client
      labels:
        app: elastic
        deployment: production
        role: client
    spec:
      containers:
        - name: elasticsearch-client
          image: rahulkrishnanfs/docker-elasticsearch-kubernetes:1.0
          ports:
            - containerPort: 9200
              name: restapi
            - containerPort: 9300
              name: nodecom

          env:

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: "elastic"
            - name: NODE_MASTER
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: NODE_MAX_LOCAL_STORAGE_NODES
              value: "1"
            - name: INDEX_NO_OF_SHARDS
              value: "5"
            - name: INDEX_NO_OF_REPLICAS
              value: "1"
            - name: NETWORK_HOST
              value: "_non_loopback:ipv4_"
            - name: ZEN_MINIMUM_MASTER_NODES
              value: "1"
            - name: MULTICAST_ENABLED
              value: "false"
