apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-master
  labels:
    app: elastic
    deployment: production
    role: master
spec:
  replicas: 1
  template:
    metadata:
      name: elasticsearch-master
      labels:
        app: elastic
        deployment: production
        role: master
  spec:
    containers:
        - name: elasticsearch-master
          image: quay.io/rahulkrishnanfs/docker-elasticsearch-kubernetes:1.0
          ports:
            - containerPort: 9200
              name: RESTAPI_access
            - containerPort: 9300
              name: node_communication

          env:

            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: elastic
            - name: NODE_MASTER
              value: true
            - name: NODE_DATA
              value: false
            - name: NODE_MAX_LOCAL_STORAGE_NODES
              value:  1
            - name: INDEX_NO_OF_SHARDS
              value: 5
            - name: INDEX_NO_OF_REPLICAS
              value: 1
            - name: NETWORK_HOST
              value: _non_loopback:ipv4_
            - name: ZEN_MINIMUM_MASTER_NODES
              value: 1
            - name: MULTICAST_ENABLED
              value: false
