apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elastic
    role: master
spec:
  selector:
    app: elastic
    deployment: production
  type: LoadBalancer
  ports:
    - name: http
      port: 9200
      protocol: TCP

