apiVersion: v1
kind: Service
metadata:
  name: elastic-discovery
  labels:
    app: elastic
    role: master
spec:
  selector:
    app: elastic
    deployment: production
  ports:

    - name: nodecom
      port: 9300
      protocol: TCP
